[mypy]
python_version = 3.10
warn_unused_configs = False
warn_incomplete_stub = True
disallow_untyped_defs = True
mypy_path = stubs
ignore_missing_imports = True
cache_dir = .cache/.mypy_cache
implicit_reexport = False
strict_equality = True
strict_optional = True
no_implicit_optional = True
