#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2025-2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

"""Shared regression test runner for device-specific configuration tests.

This module provides common infrastructure for validating functional equivalence
between the legacy Perl configtool and SMCT across different device families.

**Comparison Method:**
The test strips comments, copyright headers, and formatting differences before
comparing the remaining C code (preprocessor directives, struct initializers,
macro definitions).

**What is validated:**
- Identical #define names and values
- Identical struct initializer content
- Identical macro definitions and expansion

**What is intentionally ignored:**
- Copyright year differences
- Comment wording and placement
- Whitespace, indentation, and alignment
- Hexadecimal letter case (0xabc vs 0xABC)
- Extra blank lines

**Why these differences are acceptable:**
SMCT is a complete rewrite with enhanced diagnostics and richer output formatting,
not a byte-for-byte clone of the Perl implementation. Functional equivalence is
the validation target, not identical formatting.

**Note on config_fusa.h:**
The FuSa configuration header (config_fusa.h) is SMCT-only and not generated by
the legacy Perl tool. It is tested separately in regression_fusa_test.py.
"""

import logging
import os.path
import shutil
from tempfile import TemporaryDirectory
from typing import Any, Set

import pytest

from smct import utils
from tests.test_utils import execute_binary, execute_cli, get_smct_root
from tests.utils.file_diff import FileDiffer
from tests.utils.smct_output_validator import SmctOutputValidator

logger = logging.getLogger()

# Shared directory constants
SM_FW_CONFIGS_DIR = os.path.abspath(os.path.join(get_smct_root(), "test_resources", "configs"))
SMCT_CONFIGS_DIR = os.path.abspath(os.path.join(get_smct_root(), "test_resources", "configs_test"))

# Perl configtool subprocess timeout, with headroom for concurrent runs under xdist worksteal.
PERL_TIMEOUT_SECONDS = 600


def find_firmware_root() -> str:
    """Locate and return the absolute firmware root directory.

    Calls pytest.fail() if the directory cannot be found.

    Returns:
        Absolute path to the firmware root directory.
    """
    firmware_root_temp = utils.find_firmware_root_dir(os.path.join(get_smct_root(), ".."))
    if firmware_root_temp is None:
        pytest.fail("Could not find firmware root directory")
    return os.path.abspath(firmware_root_temp)  # type: ignore[arg-type]


def run_device_regression_test(capsys: Any, config: str, expected_diff_files: Set[str] | None = None) -> None:
    """Run regression test comparing Perl configtool vs SMCT output for a device.

    Creates temporary directories for golden (Perl) and test (SMCT) outputs,
    executes both tools with the same configuration file, and validates that
    the generated C headers are functionally equivalent.

    Args:
        capsys: Pytest capsys fixture for capturing stdout/stderr
        config: Absolute path to the .cfg configuration file to test

    Raises:
        pytest.fail: If firmware root cannot be found, SMCT execution fails, or
                     output files differ beyond acceptable formatting variations
    """
    with TemporaryDirectory() as golden, TemporaryDirectory() as test:
        config_stem = os.path.splitext(os.path.basename(config))[0]
        logger.info("Starting regression test for %s configuration", config_stem)
        logger.info("Golden sample folder: %s", golden)
        logger.info("Test sample folder: %s", test)
        logger.info("SMCT root: %s", get_smct_root())

        # Locate firmware root directory
        firmware_root = find_firmware_root()
        config_tool = os.path.join(firmware_root, "configs", "configtool.pl")
        diff_folder = os.path.join(get_smct_root(), "test_results", "test_regression_cfgs", config_stem)

        logger.info("Diff folder: %s", diff_folder)
        logger.info("Firmware path: %s", firmware_root)
        logger.info("Config tool: %s", config_tool)
        logger.info("CFG file: %s", config)

        # 1. Run Perl legacy tool

        # Check if Perl is available
        if shutil.which("perl") is None:
            pytest.skip("Perl not found in PATH, skipping Perl comparison")

        # Check if configtool.pl exists
        if not os.path.isfile(config_tool):
            pytest.skip(f"Perl configtool not found at {config_tool}, skipping comparison")

        perl_code, _, perl_stderr = execute_binary("perl", [config_tool, "-i", config, "-o", golden], timeout=PERL_TIMEOUT_SECONDS)

        if perl_code != 0:
            logger.warning(
                "Perl configtool rejected config (exit %d), skipping comparison:\n%s",
                perl_code,
                perl_stderr,
            )
            pytest.skip(f"Perl configtool exit {perl_code}")

        logger.info("Finished legacy tool execution for %s configuration", config_stem)

        # 2. Run SMCT
        code, _, _ = execute_cli(capsys, ["-c", config, "-o", test, "--sm_dir", firmware_root])
        assert code == 0

        # 3. Validate SMCT output (self-consistency)
        validator = SmctOutputValidator(test)
        is_valid, issues = validator.validate()
        assert is_valid, "SMCT output validation failed:\n" + "\n".join(issues)

        # 4. Compare outputs
        differ = FileDiffer(FileDiffer.default_c_files_pattern, golden, test, diff_folder)
        if not differ.check_differences(exclude_files=expected_diff_files):
            different_files = differ.get_error_files()
            difference = []
            for diff_file in different_files:
                difference.append(f"File {diff_file} differs:")
                difference.append(differ.get_error(diff_file))
            pytest.fail("\n".join(difference))
