#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
"""Unit tests for smct.generation.export_cfg CfgExporter and GenCfgHeading."""

# pylint: disable=protected-access

import io
import os
from pathlib import Path
from unittest.mock import Mock

from smct.configuration.confdata import ConfigurationData
from smct.generation.export_cfg import CfgExporter, GenCfgHeading
from smct.generation.generator import GenHeading
from smct.owners.owner_agent import MailboxMu, ScmiAgent, ScmiChannel, SmtChannel
from smct.owners.owner_base import AssignedDefine, AssignedResource
from smct.owners.owner_dom import DOM
from smct.owners.owner_lm import LM, MSEL
from smct.resources.resource_base import AtomicResource
from smct.utils import FormatedInt
from tests import test_utils


def _generate_and_read(conf: ConfigurationData, generator: CfgExporter, directory: Path) -> str:
    """Generate a .cfg file and return its content."""
    generator.generate(conf, str(directory))
    file_path = os.path.join(str(directory), generator._get_output_file_name())
    with open(file_path, "r", encoding="utf-8") as fh:
        return fh.read()


class TestGenCfgHeading:
    """Tests for GenCfgHeading."""

    def test_gen_cfg_heading_inherits_from_gen_heading(self) -> None:
        """Test that GenCfgHeading is a subclass of GenHeading."""
        heading = GenCfgHeading("Test")
        assert isinstance(heading, GenHeading)

    def test_gen_cfg_heading_uses_hash_comment_chars(self) -> None:
        """Test that GenCfgHeading uses '#' as both left and right comment chars."""
        heading = GenCfgHeading("Board")
        assert heading._left == "#"
        assert heading._right == "#"

    def test_gen_cfg_heading_get_string_contains_hash_borders(self) -> None:
        """Test that the rendered heading contains '#---#' style borders."""
        heading = GenCfgHeading("Board")
        heading.print_head()
        text = heading.get_head_string()
        assert "#" in text
        assert "Board" in text

    def test_gen_cfg_heading_prints_comment_with_hash_prefix(self) -> None:
        """Test that the comment line starts with '# <text>'."""
        heading = GenCfgHeading("My Section")
        heading.print_head()
        text = heading.get_string()
        assert "# My Section" in text

    def test_gen_cfg_heading_full_output_contains_separator_lines(self) -> None:
        """Test that the heading output contains horizontal separator lines."""
        heading = GenCfgHeading("Devices")
        heading.print_head()
        output_lines = heading.get_string().splitlines()
        separator_lines = [line for line in output_lines if "---" in line and line.startswith("#")]
        assert len(separator_lines) >= 2


class TestCfgExporter:
    """Tests for CfgExporter."""

    def test_get_output_file_name_returns_configured_filename(self) -> None:
        """Test that the exporter uses the filename provided at construction."""
        exporter = CfgExporter("my_config.cfg")
        assert exporter._get_output_file_name() == "my_config.cfg"

    def test_generate_minimal_config_produces_cfg_file(self, tmp_path: Path) -> None:
        """Test that generate() produces the expected .cfg output file."""
        directory = tmp_path
        exporter = CfgExporter("out.cfg")
        conf = ConfigurationData()
        conf.set_doxygen_name_descr("TestConfig", "Test description")

        exporter.generate(conf, str(directory))

        assert os.path.isfile(os.path.join(str(directory), "out.cfg"))

    def test_generate_includes_copyright_header(self, tmp_path: Path) -> None:
        """Test that the generated file includes the copyright notice."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()

        content = _generate_and_read(conf, exporter, directory)

        assert "NXP" in content

    def test_generate_includes_generated_by_comment(self, tmp_path: Path) -> None:
        """Test that the file contains the 'generated by smct.py' comment."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()

        content = _generate_and_read(conf, exporter, directory)

        assert "generated by smct.py" in content

    def test_generate_includes_make_macro_with_device(self, tmp_path: Path) -> None:
        """Test that the MAKE macro with device info is written."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        conf.set_device("MIMX95", "mcimx95evk")

        content = _generate_and_read(conf, exporter, directory)

        assert "MAKE" in content
        assert "soc=MIMX95" in content

    def test_generate_includes_dox_macro(self, tmp_path: Path) -> None:
        """Test that the DOX macro with dox name is written."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        conf.set_doxygen_name_descr("MX95EVK", "i.MX95 EVK Configuration")

        content = _generate_and_read(conf, exporter, directory)

        assert "DOX" in content
        assert "name=MX95EVK" in content

    def test_generate_includes_board_section_heading(self, tmp_path: Path) -> None:
        """Test that the Board section heading using '#' chars is generated."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()

        content = _generate_and_read(conf, exporter, directory)

        assert "# Board" in content

    def test_generate_includes_board_uart_instance(self, tmp_path: Path) -> None:
        """Test that BOARD DEBUG_UART_INSTANCE appears in output."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        conf.set_debug_uart_instance(FormatedInt(3))
        conf.set_debug_uart_baudrate(FormatedInt(115200))

        content = _generate_and_read(conf, exporter, directory)

        assert "DEBUG_UART_INSTANCE=3" in content
        assert "DEBUG_UART_BAUDRATE=115200" in content

    def test_generate_includes_common_defines_heading(self, tmp_path: Path) -> None:
        """Test that the 'Common Defines' section heading is generated."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()

        content = _generate_and_read(conf, exporter, directory)

        assert "# Common Defines" in content

    def test_generate_includes_user_resources_heading(self, tmp_path: Path) -> None:
        """Test that the 'User Resources' section heading is generated."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()

        content = _generate_and_read(conf, exporter, directory)

        assert "# User Resources" in content

    def test_generate_includes_end_of_file_comment(self, tmp_path: Path) -> None:
        """Test that the footer 'End of generated configuration file' comment appears."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()

        content = _generate_and_read(conf, exporter, directory)

        assert "End of generated configuration file" in content

    def test_generate_board_section_includes_i2c_settings(self, tmp_path: Path) -> None:
        """Test that PMIC I2C instance and baudrate appear in the Board section."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        conf.set_pmic_i2c_instance(FormatedInt(2))
        conf.set_pmic_i2c_baudrate(FormatedInt(400000))

        content = _generate_and_read(conf, exporter, directory)

        assert "I2C_INSTANCE=2" in content
        assert "I2C_BAUDRATE=400000" in content

    def test_generate_skips_device_include_when_no_device(self, tmp_path: Path) -> None:
        """Test that no include line is generated when device is not set."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()

        content = _generate_and_read(conf, exporter, directory)

        assert "include" not in content or "smct" not in content

    def test_print_defines_empty_dict_produces_no_define_entries(self) -> None:
        """Test that print_defines with empty dict adds nothing to output."""
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        exporter.print_defines({})
        assert buf.getvalue() == ""

    def test_generate_with_fusa_integer_define_produces_fusa_def_macro(self, tmp_path: Path) -> None:
        """Test that a FUSA integer define produces a FUSA_DEF macro in .cfg output."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        conf.add_fusa_config("MY_FUSA_DEF", 42, "Test comment")

        content = _generate_and_read(conf, exporter, directory)

        assert "FUSA_DEF" in content
        assert "MY_FUSA_DEF=42" in content

    def test_generate_with_fusa_string_define_wraps_in_quotes(self, tmp_path: Path) -> None:
        """Test that a FUSA string define (without C suffixes) is wrapped in quotes."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        # Use a value without C suffix letters (L, LL, U, UL, ULL) to trigger the quoted branch
        conf.add_fusa_config("MY_STR_DEF", "ABCDEF", None)

        content = _generate_and_read(conf, exporter, directory)

        assert 'MY_STR_DEF="ABCDEF"' in content

    def test_generate_with_mak_variable_value_1_outputs_var_flag(self, tmp_path: Path) -> None:
        """Test that MAK variable with value 1 produces 'var=NAME' in MAKE macro."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        conf.set_mak_variable("TEST_FLAG", 1)

        content = _generate_and_read(conf, exporter, directory)

        assert "var=TEST_FLAG" in content

    def test_generate_with_mak_variable_other_value_outputs_var_with_pipe(self, tmp_path: Path) -> None:
        """Test that MAK variable with value != 1 produces 'var=NAME|VALUE' in MAKE macro."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        conf.set_mak_variable("LEVEL", 3)

        content = _generate_and_read(conf, exporter, directory)

        assert "var=LEVEL|3" in content

    def test_generate_with_lm_with_msel_produces_lm_section(self, tmp_path: Path) -> None:
        """Test that a config with an LM (having default msel) produces an LM section."""
        test_utils.set_up()
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        lm = LM("lm0", 0, "TestLM", None, None, None, None, None, False)
        lm.get_msel(0)  # ensure default MSEL exists (needed for lm.get_boot())
        conf.add_lm(lm)

        content = _generate_and_read(conf, exporter, directory)

        assert "LM0" in content
        assert "TestLM" in content

    def test_generate_with_lm_having_extra_msel_outputs_mode_comment(self, tmp_path: Path) -> None:
        """Test that an LM with a non-zero msel index produces an operation-mode comment."""
        test_utils.set_up()
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        lm = LM("lm0", 0, "LM0", None, None, None, None, None, False)
        lm.get_msel(0)
        lm.get_msel(1, boot=2)
        conf.add_lm(lm)

        content = _generate_and_read(conf, exporter, directory)

        assert "Operation mode mSel=1" in content

    def test_print_defines_with_assigned_define_outputs_define_line(self) -> None:
        """Test that print_defines with a non-empty AssignedDefine writes output."""
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        define = AssignedDefine("MY_DEFINE", "val=42")
        exporter.print_defines({"MY_DEFINE": define})

        output = buf.getvalue()
        assert "MY_DEFINE" in output

    def test_print_defines_with_dirty_flag_false_comments_out_define(self) -> None:
        """Test that print_defines with set_dirty_flag=False comments out the define."""
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        define = AssignedDefine("MY_DEFINE", "val=42")
        exporter.print_defines({"MY_DEFINE": define}, set_dirty_flag=False)

        output = buf.getvalue()
        assert "# MY_DEFINE" in output

    def test_print_resource_assignment_with_simple_resource(self) -> None:
        """Test that print_resource_assignment writes the resource name."""
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mock_assr = Mock(spec=AssignedResource)
        mock_assr.get_resource.return_value.get_name.return_value = "SOME_RESOURCE"
        mock_assr.get_defines.return_value = []
        mock_assr.get_filtered_params.return_value = {}
        mock_assr.is_dirty.return_value = True

        exporter.print_resource_assignment(mock_assr, True)

        assert "SOME_RESOURCE" in buf.getvalue()

    def test_print_resource_assignment_with_bool_param_outputs_flag_name(self) -> None:
        """Test that a bool param is emitted without '=' (as a flag)."""
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mock_assr = Mock(spec=AssignedResource)
        mock_assr.get_resource.return_value.get_name.return_value = "RES1"
        mock_assr.get_defines.return_value = []
        mock_assr.get_filtered_params.return_value = {"test": True}
        mock_assr.is_dirty.return_value = True

        exporter.print_resource_assignment(mock_assr, True)

        output = buf.getvalue()
        assert "test" in output

    def test_print_resource_assignment_with_size_and_begin_outputs_end_address(self) -> None:
        """Test that size param with begin is converted to end= address."""
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mock_assr = Mock(spec=AssignedResource)
        mock_assr.get_resource.return_value.get_name.return_value = "MEM_RES"
        mock_assr.get_defines.return_value = []
        mock_assr.get_filtered_params.return_value = {"begin": "4096", "size": "256"}
        mock_assr.is_dirty.return_value = True

        exporter.print_resource_assignment(mock_assr, True)

        output = buf.getvalue()
        assert "end=" in output
        # begin=4096, size=256 → end = hex(4096 + 256 - 1) = hex(4351) = "0x10ff"
        assert "end=0x10ff" in output

    def test_print_resource_assignment_with_key_value_param(self) -> None:
        """Test that a non-bool non-size param is emitted as key=value."""
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mock_assr = Mock(spec=AssignedResource)
        mock_assr.get_resource.return_value.get_name.return_value = "RES2"
        mock_assr.get_defines.return_value = []
        mock_assr.get_filtered_params.return_value = {"perm": "rw"}
        mock_assr.is_dirty.return_value = True

        exporter.print_resource_assignment(mock_assr, True)

        output = buf.getvalue()
        assert "perm=rw" in output

    def test_print_resource_assignments_with_dirty_assignments_outputs_assigned_header(self) -> None:
        """Test that dirty assignments produce '# Assigned resources' header."""
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mock_owner = Mock()
        mock_assr = Mock(spec=AssignedResource)
        mock_assr.get_resource.return_value.get_name.return_value = "RES_A"
        mock_assr.get_defines.return_value = []
        mock_assr.get_filtered_params.return_value = {}
        mock_assr.is_dirty.return_value = True
        mock_owner.get_assigned_resources.return_value = [mock_assr]
        mock_owner.is_dirty.return_value = True

        exporter.print_resource_assignments(mock_owner)

        assert "# Assigned resources" in buf.getvalue()

    def test_print_resource_assignments_with_foreign_assignments_outputs_externally_header(self) -> None:
        """Test that non-dirty assignments produce '# Resources assigned externally' header."""
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mock_owner = Mock()
        mock_assr = Mock(spec=AssignedResource)
        mock_assr.get_resource.return_value.get_name.return_value = "RES_B"
        mock_assr.get_defines.return_value = []
        mock_assr.get_filtered_params.return_value = {}
        mock_assr.is_dirty.return_value = False  # foreign assignment
        mock_owner.get_assigned_resources.return_value = [mock_assr]
        mock_owner.is_dirty.return_value = True

        exporter.print_resource_assignments(mock_owner)

        assert "# Resources assigned externally" in buf.getvalue()

    def test_generate_with_fusa_task_produces_fusa_task_macro(self, tmp_path: Path) -> None:
        """Test that a FUSA task produces a FUSA_TASK macro with correct fields."""
        test_utils.set_up()
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        conf.add_fusa_task("MY_TASK", "10ms", "handler", "task comment")

        content = _generate_and_read(conf, exporter, directory)

        assert "FUSA_TASK" in content
        assert "task=MY_TASK" in content
        assert "period=10ms" in content

    def test_generate_with_fusa_task_no_comment_produces_task_without_comment(self, tmp_path: Path) -> None:
        """Test that a FUSA task without comment still produces FUSA_TASK macro."""
        test_utils.set_up()
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        conf.add_fusa_task("TASK2", "5ms", None, None)

        content = _generate_and_read(conf, exporter, directory)

        assert "FUSA_TASK" in content
        assert "task=TASK2" in content

    def test_generate_with_dirty_dom_having_no_resources_produces_dom_heading(self, tmp_path: Path) -> None:
        """Test that a dirty DOM with no resources produces a domain section heading."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        dom = DOM("dom1", 1, "TestDom")
        conf.add_dom(dom)

        content = _generate_and_read(conf, exporter, directory)

        assert "TestDom" in content
        assert "DOM1" in content

    def test_generate_with_non_dirty_dom_produces_commented_dom_macro(self, tmp_path: Path) -> None:
        """Test that a non-dirty (foreign) DOM produces a commented-out DOM macro."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        dom = DOM("dom2", 2, "ForeignDom")
        dom.set_dirty_flag(False)
        conf.add_dom(dom)

        content = _generate_and_read(conf, exporter, directory)

        assert "defined externally" in content
        assert "# DOM2" in content

    def test_generate_with_dirty_dom_having_resources_produces_dom_section(self, tmp_path: Path) -> None:
        """Test that a dirty DOM with resources produces the plain domain section heading."""
        directory = tmp_path
        exporter = CfgExporter("cfg.cfg")
        conf = ConfigurationData()
        dom = DOM("dom3", 3, "ResourceDom")
        # Inject a mock assigned resource directly
        mock_assr = Mock(spec=AssignedResource)
        mock_assr.get_resource.return_value.get_name.return_value = "SOME_RES"
        mock_assr.get_defines.return_value = []
        mock_assr.get_filtered_params.return_value = {}
        mock_assr.is_dirty.return_value = True
        dom._resources.append(mock_assr)  # type: ignore[attr-defined]
        conf.add_dom(dom)

        content = _generate_and_read(conf, exporter, directory)

        assert "ResourceDom" in content

    def test_print_mailbox_mu_produces_mailbox_with_mu_field(self) -> None:
        """Test that print_mailbox for MailboxMu emits MAILBOX with mu= field."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mailbox = MailboxMu(3, None, None, None)

        exporter.print_mailbox(mailbox)

        output = buf.getvalue()
        assert "MAILBOX" in output
        assert "mu=3" in output

    def test_print_mailbox_mu_with_sma_produces_sma_field(self) -> None:
        """Test that MailboxMu with sma emits sma= field in MAILBOX macro."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mailbox = MailboxMu(1, 5, FormatedInt(0x8000), None)

        exporter.print_mailbox(mailbox)

        output = buf.getvalue()
        assert "sma=" in output

    def test_print_mailbox_mu_with_test_produces_test_field(self) -> None:
        """Test that MailboxMu with test= produces the test field in output."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mailbox = MailboxMu(2, 7, None, None)

        exporter.print_mailbox(mailbox)

        output = buf.getvalue()
        assert "test=7" in output

    def test_print_scmi_channel_produces_channel_macro_with_rpc_and_type(self) -> None:
        """Test that print_scmi_channel emits CHANNEL with rpc= and type= fields."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mock_owner = Mock()
        mock_owner.get_id.return_value = "agent0"
        scmi_ch = ScmiChannel(mock_owner, "a2p", None, None, None)

        exporter.print_scmi_channel(scmi_ch)

        output = buf.getvalue()
        assert "CHANNEL" in output
        assert "rpc=scmi" in output
        assert "type=a2p" in output

    def test_print_scmi_channel_with_smt_xport_produces_db_field(self) -> None:
        """Test that ScmiChannel with SmtChannel xport emits db= field."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        mock_owner = Mock()
        mock_owner.get_id.return_value = "agent0"
        scmi_ch = ScmiChannel(mock_owner, "a2p", None, None, None)
        smt_ch = SmtChannel(0, None)
        scmi_ch.set_xport_channel(smt_ch)

        exporter.print_scmi_channel(scmi_ch)

        output = buf.getvalue()
        assert "db=0" in output

    def test_print_agent_with_mu_mailbox_and_scmi_channel_produces_agent_heading(self) -> None:
        """Test that print_agent with MailboxMu and SCMI channel emits SCMI Agent heading."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        lm = LM("lm0", 0, "TestLM", "scmi", None, None, None, None, False)
        agent = ScmiAgent("agent0", lm, "Agent0", False)
        lm.add_agent(agent)
        mailbox = MailboxMu(1, None, None, None)
        agent.add_mailbox(mailbox)
        scmi_ch = ScmiChannel(agent, "a2p", None, None, None)
        agent.add_channel(scmi_ch)

        exporter.print_agent(agent)

        output = buf.getvalue()
        assert "SCMI Agent" in output
        assert "Agent0" in output

    def test_print_agent_with_dup_includes_dup_field(self) -> None:
        """Test that a dup agent emits dup= field in its macro."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        lm = LM("lm0", 0, "TestLM", "scmi", None, None, None, None, False)
        agent_src = ScmiAgent("agent0", lm, "SrcAgent", False)
        lm.add_agent(agent_src)
        agent_dup = ScmiAgent("agent1", lm, "DupAgent", False)
        agent_dup.duplicate(agent_src, 0)
        lm.add_agent(agent_dup)

        exporter.print_agent(agent_dup)

        output = buf.getvalue()
        assert "dup=0" in output

    def test_print_msel_with_start_sequence_produces_start_sequence_comment(self) -> None:
        """Test that print_msel with a start sequence emits '# Start sequence'."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        lm = LM("lm0", 0, "LM0", None, None, None, None, None, False)
        msel = MSEL(lm, 0, None, None)
        mock_res = Mock(spec=AtomicResource)
        mock_res.get_name.return_value = "CPU_A55_0"
        msel.add_start_stop(True, False, mock_res, "1")

        exporter.print_msel(msel)

        output = buf.getvalue()
        assert "Start sequence" in output

    def test_print_msel_with_test_start_stop_appends_test_flag(self) -> None:
        """Test that a start_stop with test=True appends 'test' flag."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        lm = LM("lm0", 0, "LM0", None, None, None, None, None, False)
        msel = MSEL(lm, 0, None, None)
        mock_res = Mock(spec=AtomicResource)
        mock_res.get_name.return_value = "CPU_A55_0"
        msel.add_start_stop(True, True, mock_res, "1")

        exporter.print_msel(msel)

        output = buf.getvalue()
        assert "test" in output

    def test_print_msel_with_stop_sequence_produces_stop_sequence_comment(self) -> None:
        """Test that print_msel with a stop sequence emits '# Stop sequence'."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        lm = LM("lm0", 0, "LM0", None, None, None, None, None, False)
        msel = MSEL(lm, 0, None, None)
        mock_res = Mock(spec=AtomicResource)
        mock_res.get_name.return_value = "CPU_A55_0"
        msel.add_start_stop(False, False, mock_res, "1")  # is_start=False → stop

        exporter.print_msel(msel)

        output = buf.getvalue()
        assert "Stop sequence" in output

    def test_print_msel_nonzero_msel_produces_operation_mode_comment(self) -> None:
        """Test that a non-zero msel index produces operation mode comment and MODE macro."""
        test_utils.set_up()
        exporter = CfgExporter("cfg.cfg")
        buf = io.StringIO()
        exporter._open_file = buf
        lm = LM("lm0", 0, "LM0", None, None, None, None, None, False)
        msel = MSEL(lm, 2, 1, None)  # msel index = 2

        exporter.print_msel(msel)

        output = buf.getvalue()
        assert "Operation mode mSel=2" in output
        assert "MODE" in output
