#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
"""Module for generating configuration file in backward-compatible .cfg format"""

import os
from typing import Dict, List

from smct.configuration.confdata import ConfigurationData
from smct.configuration.confdata_fusa import FusaDefine, FusaTask
from smct.generation.generator import GenCfgMacro, GeneratorBase, GenHeading
from smct.owners.owner_agent import Mailbox, MailboxMu, ScmiAgent, ScmiChannel, SmtChannel
from smct.owners.owner_base import AssignedDefine, AssignedResource, ResourceOwner
from smct.owners.owner_lm import MSEL
from smct.resources.resource_database_provider import ResourceDatabaseProvider


class GenCfgHeading(GenHeading):
    """Headings in .cfg syntax"""

    def __init__(self, comment: str):
        """Initialize a .cfg format heading.

        Args:
            comment: The comment text for the heading
        """
        super().__init__(comment, ("#", "#"))


class CfgExporter(GeneratorBase):
    """Exporting native cfg file"""

    def __init__(self, filename: str):
        """Initialize the cfg file exporter.

        Args:
            filename: The output filename for the cfg file
        """
        super().__init__()
        self._filename = filename

    def _get_output_file_name(self) -> str:
        """Get the output filename.

        Returns:
            The configured output filename
        """
        return self._filename

    def _get_copyright_comment_beginning(self) -> str:
        """Returns the copyright comment beginning

        Returns:
            Empty string for cfg format
        """
        return ""

    def _get_copyright_comment_prefix(self) -> str:
        """Returns the copyright comment line prefix

        Returns:
            Hash character for cfg format comments
        """
        return "##"

    def _get_copyright_comment_ending(self) -> str:
        """Returns the copyright comment ending

        Returns:
            Empty string for cfg format
        """
        return ""

    def _print_header(self) -> None:
        """Print the file header including copyright and configuration info."""
        self._print_copyright()
        self._print("\n# This file has been generated by smct.py configuration tool\n")
        if self._conf:
            self._print(f"# SM configuration file for {self._conf.get_board_name()}\n")

    def print_content(self) -> None:
        """Print the main configuration content to the output file."""
        if self._conf:
            conf: ConfigurationData = self._conf

            # MAKE    soc=MIMX95, board=mcimx95evk, build=gcc_cross
            make_macro = GenCfgMacro("MAKE")
            make_macro.append(f"soc={conf.get_device_name()}")
            make_macro.append(f"board={conf.get_board_name()}")
            make_macro.append(f"build={conf.get_build_tool()}")
            self._print(make_macro.get())

            # DOX     name=MX95EVK, desc="i.MX95 EVK Configuration Data"
            dox_macro = GenCfgMacro("DOX")
            dox_macro.append(f"name={conf.get_doxygen_name()}")
            dox_macro.append(f'desc="{conf.get_doxygen_description()}"')
            self._print(dox_macro.get())

            # include ../devices/MIMX95/configtool/device.cfg
            device = conf.get_device_name()
            if device:
                path = os.path.join(os.path.normpath(conf.get_sm_fw_root_directory()), "devices", device, "configtool", "device.cfg")
                include = f"\ninclude {path}"
                self._print(include)

            # BOARD parameters
            self.print_generator(GenCfgHeading("Board"))
            self._print(GenCfgMacro("BOARD", f"DEBUG_UART_INSTANCE={conf.get_debug_uart_instance()}").get())
            self._print(GenCfgMacro("BOARD", f"DEBUG_UART_BAUDRATE={conf.get_debug_uart_baudrate()}").get())
            self._print(GenCfgMacro("BOARD", f"I2C_INSTANCE={conf.get_pmic_i2c_instance()}").get())
            self._print(GenCfgMacro("BOARD", f"I2C_BAUDRATE={conf.get_pmic_i2c_baudrate()}").get())

            # FUSA parameters
            fusa_defines: List[FusaDefine] = conf.get_fusa_configs()
            suffixes = ["L", "LL", "U", "UL", "ULL"]
            if fusa_defines:
                self.print_generator(GenCfgHeading("FUSA Configuration Values"))
                for define in fusa_defines:
                    if any(subs in str(define.get_value()) for subs in suffixes) or isinstance(define.get_value(), int):
                        def_macro = GenCfgMacro("FUSA_DEF", f"{define.get_name()}={define.get_value()}")
                    else:
                        def_macro = GenCfgMacro("FUSA_DEF", f'{define.get_name()}="{define.get_value()}"')
                    if define.get_comment():
                        def_macro.append(f'comment="{define.get_comment()}"')
                    self._print(def_macro.get())

            # FUSA tasks
            fusa_tasks: List[FusaTask] = conf.get_fusa_tasks()
            if fusa_tasks:
                self.print_generator(GenCfgHeading("FUSA Periodic Tasks"))
                for task in fusa_tasks:
                    task_macro = GenCfgMacro("FUSA_TASK")
                    task_macro.append(f"task={task.get_name()}")
                    task_macro.append(f"period={task.get_period()}")
                    task_macro.append(f"type={task.get_task_type()}")
                    if task.get_comment():
                        task_macro.append(f'comment="{task.get_comment()}"')
                    self._print(task_macro.get())

            # Common defines
            self.print_generator(GenCfgHeading("Common Defines"))
            self.print_defines(conf.get_common_defines())

            # User resource
            self.print_generator(GenCfgHeading("User Resources"))
            for resource in ResourceDatabaseProvider.get_database().user_resources_list():
                rsrc_macro = GenCfgMacro(resource.get_name(), colon_macro=True)
                for param in resource.get_parameters():
                    rsrc_macro.append(param)
                for atom in resource.get_atomic_resources():
                    rsrc_macro.append(atom.get_name())
                self._print(rsrc_macro.get())

            # Domains
            for dom in conf.get_all_non_lm_domains():
                res_count = len(dom.get_assigned_resources())
                dom_macro = GenCfgMacro(f"DOM{dom.get_did()}", f'name="{dom.get_name()}", did={dom.get_did()}')

                if not dom.is_dirty():
                    # foreign DOM must be commented out not to become locally-defined
                    self.print_generator(GenCfgHeading(f"{dom.get_name()} Domain is defined externally"))
                    dom_macro.set_commented_out()
                elif res_count == 0:
                    self.print_generator(GenCfgHeading(f"{dom.get_name()} Domain has no assigned resources"))
                else:
                    self.print_generator(GenCfgHeading(f"{dom.get_name()} Domain"))

                # print the DOM command
                self._print(dom_macro.get())
                self._print("")

                # print the DOM's defines
                self.print_defines(dom.get_defines(), set_dirty_flag=dom.is_dirty())

                # print the DOM's resources
                self.print_resource_assignments(dom)

            # LMs
            keys_normal = ["did", "rpc", "safe", "group", "rtime", "auto"]
            keys_novalue = ["default"]
            for lm in conf.get_all_lms():
                boot_val = lm.get_boot() if lm.get_boot() else 0
                skip_val = 1 if lm.get_skip() else None
                keys_special = [("boot", boot_val), ("skip", skip_val)]
                self.print_generator(GenCfgHeading(f'LM "{lm.get_name()}" {lm.get_safe()}'))
                lm_macro = GenCfgMacro(f"LM{conf.get_lm_id(lm)}", f'name="{lm.get_name()}"')
                lm_macro.append_json_values(lm.get_assignment_json(), keys_normal, keys_novalue, keys_special)
                self._print(lm_macro.get())
                self._print("")
                self.print_defines(lm.get_defines())

                # LM mSels
                for msel in lm.get_all_msels():
                    self.print_msel(msel)

                # not expected for LM to have its own assignments, but anyway
                if len(lm.get_assigned_resources()):
                    self.print_resource_assignments(lm)

                # RPC agents
                for agent in lm.get_all_agents():
                    self.print_agent(agent)

    def print_defines(self, defines: Dict[str, AssignedDefine], set_dirty_flag: bool = True) -> None:
        """Print assignment templates passed as a dictionary of defines.

        Args:
            defines: Dictionary of define names to AssignedDefine objects
            set_dirty_flag: Whether the force all defines to be treated as dirty
        """
        for name in defines:
            define: AssignedDefine = defines[name]
            define_macro = GenCfgMacro(name, colon_macro=True)
            define_macro.append_json_values(define.get_params(), all_keys=True)
            if not set_dirty_flag:
                define_macro.set_commented_out(commented_out=True)
            self._print(define_macro.get())

    def print_resource_assignment(self, assignment: AssignedResource, owner_dirty_flag: bool) -> None:
        """Print single assigned resource for a given owner.

        Args:
            assignment: The resource to print
            owner_dirty_flag: Whether resource owner has set dirty flag
        """
        assignment_macro = GenCfgMacro(assignment.get_resource().get_name(), value_tab_pos=32)

        for define in assignment.get_defines():
            assignment_macro.append(define.get_name())

        params = assignment.get_filtered_params()
        for param in params:
            if isinstance(params[param], bool):
                assignment_macro.append(param)  # e.g. print 'test' instead of 'test=True'
            elif param == "size" and "begin" in params:
                # handle size parameter explicitly
                assignment_macro.append(f'end={hex(int(params["begin"]) + int(params[param]) - 1)}')
            else:
                assignment_macro.append(f"{param}={params[param]}")
        # foreign assignments are printed as commented-out
        comment_out = not assignment.is_dirty()
        assignment_macro.set_commented_out(comment_out or not owner_dirty_flag)
        self._print(assignment_macro.get())

    def print_resource_assignments(self, owner: ResourceOwner) -> None:
        """Print assigned resources for a given owner.

        Args:
            owner: The resource owner whose assignments to print
        """
        # print user-defined resources in 1st round and foreign ones in 2nd round
        # note that the round may be empty or forced-empty
        assignments: List[AssignedResource] = owner.get_assigned_resources()
        owner_dirty_flag = owner.is_dirty()
        foreign_assignments = [assignment for assignment in assignments if not assignment.is_dirty()]
        user_assignments = [assignment for assignment in assignments if assignment.is_dirty()]

        if user_assignments:
            self._print("")
            self._print("# Assigned resources")
            self._print("")
            for assignment in user_assignments:
                self.print_resource_assignment(assignment, owner_dirty_flag)
        if foreign_assignments:
            self._print("")
            self._print("# Resources assigned externally")
            self._print("")
            for assignment in foreign_assignments:
                self.print_resource_assignment(assignment, owner_dirty_flag)

    def print_msel(self, msel: MSEL) -> None:
        """Print mSel settings.

        Args:
            msel: The MSEL object to print settings for
        """
        if msel.get_msel() != 0:
            self._print("")
            self._print(f"# Operation mode mSel={msel.get_msel()}")
            self._print("")
            msel_macro = GenCfgMacro("MODE")
            msel_macro.append_json_values(msel.get_assignment_json(), keys_normal=["msel", "boot", "skip"])
            self._print(msel_macro.get())

        if msel.get_start():
            self._print("")
            self._print("# Start sequence")
            for index, ss in enumerate(msel.get_start(), 1):
                if ss:
                    start_macro = GenCfgMacro(ss.get_resources().get_name())
                    start_macro.append(f"msel={ss.get_msel().get_msel()}")
                    args = ""
                    if len(ss.get_args()):
                        args = "|" + "|".join(map(str, ss.get_args()))
                    start_macro.append(f"start={index}{args}")
                    if ss.get_test():
                        start_macro.append("test")
                    self._print(start_macro.get())

        if msel.get_stop():
            self._print("")
            self._print("# Stop sequence")
            for index, ss in enumerate(msel.get_stop(), 1):
                if ss:
                    stop_macro = GenCfgMacro(ss.get_resources().get_name())
                    stop_macro.append(f"msel={ss.get_msel().get_msel()}")
                    stop_macro.append(f"stop={index}")
                    if ss.get_test():
                        stop_macro.append("test")
                    self._print(stop_macro.get())

    def print_agent(self, agent: ScmiAgent) -> None:
        """Print SCMI_AGENT settings.

        Args:
            agent: The SCMI agent to print settings for
        """
        self.print_generator(GenCfgHeading(f'SCMI Agent "{agent.get_name()}" in LM "{agent.get_owner().get_name()}"'))
        agent_macro = GenCfgMacro(f"{agent.get_id()}")
        agent_macro.append(f'name="{agent.get_name()}"')
        if agent.get_secure():
            agent_macro.append("secure")
        self._print(agent_macro.get())
        self._print("")
        self.print_defines(agent.get_defines())
        self._print("")

        mailbox = agent.get_mailbox()
        if mailbox:
            self._print("# RPC Interface")
            self._print("")
            self.print_mailbox(mailbox)
            for ch in agent.get_all_scmi_channels():
                self.print_scmi_channel(ch)
        self.print_resource_assignments(agent)

    def print_mailbox(self, mailbox: Mailbox) -> None:
        """Print Mailbox settings.

        Args:
            mailbox: The mailbox object to print settings for
        """
        mailbox_macro = GenCfgMacro("MAILBOX")
        mailbox_macro.append(f"type={mailbox.get_type()}")
        if mailbox.get_priority() is not None:
            mailbox_macro.append(f"priority={mailbox.get_priority()}")
        if isinstance(mailbox, MailboxMu):
            mailbox_macro.append(f"mu={mailbox.get_mu()}")
            if mailbox.get_sma() is not None:
                mailbox_macro.append(f"sma={mailbox.get_sma()}")
        if mailbox.get_test() is not None:
            mailbox_macro.append(f"test={mailbox.get_test()}")
        self._print(mailbox_macro.get())

    def print_scmi_channel(self, channel: ScmiChannel) -> None:
        """Print ScmiChannel settings.

        Args:
            channel: The SCMI channel to print settings for
        """
        channel_macro = GenCfgMacro("CHANNEL")
        channel_macro.append(f"rpc={channel.get_type()}")
        channel_macro.append(f"type={channel.get_channel_type()}")

        if channel.get_sequence():
            channel_macro.append(f"sequence={channel.get_sequence()}")
        if channel.get_notify() > 0:
            channel_macro.append(f"notify={channel.get_notify()}")
        if channel.get_test():
            channel_macro.append(f"test={channel.get_test()}")

        xport = channel.get_xport_channel()
        if xport:
            channel_macro.append(f"xport={xport.get_type()}")

        if isinstance(xport, SmtChannel):
            channel_macro.append(f"db={xport.get_doorbell()}")
            if xport.get_check():
                channel_macro.append(f"check={xport.get_check()}")
        self._print(channel_macro.get())

    def print_footer(self) -> None:
        """Print the file footer."""
        self._print("\n# End of generated configuration file")
